In [23]:
import pandas as pd

df = pd.read_csv("/home/nexa-lab/Desktop/Python3/Data and IPYNB Files/Chapter 9/data/covid/covid-vaccination-doses-per-capita.csv")

df.head(10)

        Entity Code         Day  total_vaccinations_per_hundred
0  Afghanistan  AFG  2021-02-22                            0.00
1  Afghanistan  AFG  2021-02-28                            0.02
2  Afghanistan  AFG  2021-03-16                            0.13
3  Afghanistan  AFG  2021-04-07                            0.29
4  Afghanistan  AFG  2021-04-22                            0.58
5  Afghanistan  AFG  2021-05-11                            1.23
6  Afghanistan  AFG  2021-05-20                            1.33
7  Afghanistan  AFG  2021-05-24                            1.39
8  Afghanistan  AFG  2021-05-26                            1.44
9  Afghanistan  AFG  2021-05-27                            1.44

In [24]:
df["Date"] = pd.to_datetime(df["Day"], format="%Y-%m-%d", errors="coerce")

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 77859 entries, 0 to 77858
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Entity                          77859 non-null  str
 1   Code                            77859 non-null  str
 2   Day                             77859 non-null  str
 3   total_vaccinations_per_hundred  77859 non-null  float64
 4   Date                            77859 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 4.6 MB

In [26]:
df.head()

        Entity Code         Day  total_vaccinations_per_hundred       Date
0  Afghanistan  AFG  2021-02-22                            0.00 2021-02-22
1  Afghanistan  AFG  2021-02-28                            0.02 2021-02-28
2  Afghanistan  AFG  2021-03-16                            0.13 2021-03-16
3  Afghanistan  AFG  2021-04-07                            0.29 2021-04-07
4  Afghanistan  AFG  2021-04-22                            0.58 2021-04-22

In [28]:
len(df["Entity"].unique())

235